//
// Created by Ajeszny on 9/19/2026.
//

#include "types.h"
#include <string.h>

struct duplex {
    const char* extension;
    const char* type;
};

static const char *mime_extensions[] = {
        "/", "123", "2fs", "323", "3ds", "3dml", "3fs", "3g2", "3ga", "3gp",
        "3gpp", "4fs", "602", "669", "7z", "a", "a2l", "aab", "aac", "aam",
        "aas", "abw", "abw.gz", "ac", "ac3", "acc", "ace", "acu", "acutc", "acx",
        "adb", "adp", "ads", "aep", "afm", "afp", "ag", "ahead", "ai", "aif",
        "aifc", "aiff", "air", "ait", "al", "alz", "ami", "aml", "amr", "amz",
        "ani", "anim", "anim0", "anim1", "anim2", "anim3", "anim4", "anim5", "anim6", "anim7",
        "anim8", "anim9", "animj", "anx", "ape", "apk", "", "apr", "apxml", "arj",
        "arw", "as", "asc", "asf", "asm", "aso", "asp", "asr", "ass", "asx",
        "atc", "atf", "atfx", "atom", "atomcat", "atomdeleted", "atomsvc", "atx", "atxml", "au",
        "auc", "authors", "avi", "aw", "awb", "awk", "axa", "axs", "axv", "azf",
        "azs", "azw", "bac", "bak", "bas", "bat", "bcpio", "bdf", "bdm", "bed",
        "bfe", "bh2", "bib", "bin", "blend", "blender", "bmi", "bmp", "book", "box",
        "boz", "bpk", "btif", "btrfs", "bz", "bz2", "c", "c++", "c11amc", "c11amz",
        "c4d", "c4f", "c4g", "c4p", "c4u", "cab", "car", "cat", "cb7", "cbor",
        "cbr", "cbt", "cbz", "cc", "ccmp", "cct", "ccxml", "cdbcmsg", "cdf", "cdfx",
        "cdkey", "cdmia", "cdmic", "cdmid", "cdmio", "cdmiq", "cdr", "cdx", "cdxml", "cdy",
        "cea", "cellml", "cer", "cert", "cgm", "changelog", "chat", "chm", "chrt", "cif",
        "cii", "cil", "cl", "cla", "class", "clkk", "clkp", "clkt", "clkw", "clkx",
        "clp", "cls", "cmakelists.txt", "cmake", "cmc", "cmdf", "cml", "cmp", "cmsc", "cmx",
        "cod", "com", "conf", "copying", "cpio", "cpio.gz", "cpl", "cpp", "cpt", "cr2",
        "crd", "credits", "crl", "crt", "crw", "cryptonote", "cs", "csh", "csml", "csp",
        "csrattrs", "cssl", "css", "cst", "csta", "csv", "cu", "cuc", "cue", "cur",
        "curl", "cw", "cww", "cxt", "cxx", "d", "dae", "daf", "dar", "dat",
        "dataless", "davmount", "dbf", "dc", "dcd", "dcl", "dcm", "dcr", "dcurl", "dd2",
        "ddd", "dds", "deb", "def", "delta", "deploy", "der", "desktop", "dfac", "dia",
        "dic", "diff", "dii", "dir", "dis", "dist", "distz", "dit", "divx", "djv",
        "djvu", "dll", "dmg", "dms", "dna", "dng", "doc", "docbook", "docm", "docx",
        "dot", "dotm", "dotx", "dp", "dpg", "dpatch", "dra", "dsc", "dsl", "dssc",
        "dtb", "dtd", "dts", "dtshd", "dtx", "dump", "dv", "dvc", "dvi", "dvi.bz2",
        "dvi.gz", "dwf", "dwg", "dxf", "dxp", "dxr", "e", "ecelp4800", "ecelp7470", "ecelp9600",
        "ecma", "edi", "edm", "edx", "efif", "egon", "ei6", "eif", "eim", "el",
        "elc", "emf", "eml", "emma", "emotionml", "emp", "ent", "eol", "eot", "eps",
        "eps.bz2", "eps.gz", "epsf", "epsf.bz2", "epsf.gz", "epsi.gz", "epsi", "epub", "erl", "es",
        "es3", "esf", "et3", "etheme", "etx", "evy", "exe", "exi", "exr", "ext",
        "ez", "ez2", "ez3", "f", "f2fs", "f4v", "f77", "f90", "f95", "fb2",
        "fbs", "fcs", "fdf", "fdt", "fe_launch", "fg5", "fgd", "fh", "fh4", "fh5",
        "fh7", "fhc", "fif", "fig", "finf", "fit", "fits", "fl", "flac", "flc",
        "fli", "flo", "flv", "flw", "flx", "fly", "fm", "fnc", "fo", "fodb",
        "fodc", "fodf", "fodg", "fodi", "fodm", "fodp", "fods", "fodt", "for", "fpx",
        "frame", "fsc", "fst", "ftc", "fti", "fts", "fvt", "fxp", "fzs", "g2w",
        "g3", "g3w", "gac", "gb", "gba", "gbr", "gcrd", "gdl", "ged", "gedcom",
        "gen", "geo", "gex", "gf", "gg", "ggb", "ggt", "ghf", "gif", "gim",
        "glade", "gmo", "gmx", "gnc", "gnd", "gnucash", "gnumeric", "gnuplot", "gp", "gpg",
        "gph", "gplt", "gqf", "gqs", "gra", "gram", "gre", "grv", "grxml", "gs",
        "gsf", "gsheet", "gsm", "gtar", "gtkrc", "gtm", "gtw", "gv", "gvp", "gxt",
        "gz", "h", "h++", "h261", "h263", "h264", "hal", "hbci", "hdf", "heldxml",
        "hh", "hlp", "hp", "hpgl", "hpid", "hpp", "hps", "hpub", "hqx", "hs",
        "hta", "htc", "htke", "htm", "html", "htt", "hvd", "hvp", "hvs", "hwp",
        "hwt", "hxx", "i2g", "ica", "icb", "icc", "icm", "icns", "ico", "ics",
        "idl", "ief", "ifb", "iff", "ifm", "iges", "igl", "igm", "igs", "igx",
        "iif", "iii", "ilbm", "ime", "imp", "ims", "imy", "in", "ink", "inkml",
        "install", "ins", "ipfix", "ipk", "iptables", "irm", "irp", "iso", "iso9660", "isp",
        "it", "itp", "its", "itz", "ivp", "ivu", "j2k", "jad", "jam", "jar",
        "java", "jfif", "jisp", "jlt", "jng", "jnlp", "joda", "jp2", "jpc", "jpe",
        "jpeg", "jpf", "jpg", "jpgm", "jpgv", "jpm", "jpr", "jpx", "jrd", "js",
        "json", "json-patch", "jsonld", "k25", "kar", "karbon", "kdc", "kdelnk", "kexi", "kexic",
        "kexis", "kfo", "kia", "kil", "kino", "kml", "kmz", "kne", "knp", "kon",
        "kpm", "kpr", "kpt", "kra", "ksh", "ksp", "ktr", "ktx", "ktz", "kud",
        "kwd", "kwt", "la", "lasxml", "latex", "lbd", "lbe", "ldif", "les", "lha",
        "lhs", "lhz", "license", "link66", "list", "list3820", "listafp", "log", "lostsyncxml", "lostxml",
        "lrf", "lrm", "lsf", "lsx", "ltf", "ltx", "lua", "lvp", "lwo", "lwob",
        "lwp", "lws", "lxf", "ly", "lyx", "lz", "lzh", "lzma", "lzo", "m",
        "m13", "m14", "m15", "m1v", "m21", "m2a", "m2t", "m2v", "m3a", "m3u",
        "m3u8", "m4", "m4a", "m4b", "m4u", "m4v", "ma", "mab", "mads", "mag",
        "makefile", "maker", "man", "mathml", "mb", "mbk", "mbox", "mc1", "mcd", "mcurl",
        "md", "mdb", "mdi", "mdz", "me", "med", "mesh", "meta4", "metalink", "mets",
        "mf4", "mfm", "mft", "mgp", "mgz", "mht", "mhtml", "mid", "midi", "mif",
        "mime", "minipsf", "mk3d", "mka", "mkv", "mj2", "mjp2", "ml", "mli", "mlp",
        "mm", "mmd", "mmf", "mml", "mmr", "mng", "mny", "mo", "mo3", "mobi",
        "moc", "mod", "mods", "mof", "moov", "mov", "movie", "mp+", "mp2", "mp21",
        "mp2a", "mp3", "mp4", "mp4a", "mp4s", "mp4v", "mpa", "mpc", "mpd", "mpdd",
        "mpe", "mpeg", "mpf", "mpg", "mpg4", "mpga", "mpkg", "mpm", "mpn", "mpp",
        "mpt", "mpv2", "mpy", "mqy", "mrc", "mrcx", "mrl", "mrml", "mrw", "ms",
        "mscml", "mseed", "mseq", "msf", "msg", "msh", "msi", "msl", "msod", "msty",
        "msx", "mtm", "mts", "mup", "mus", "musicxml", "mvb", "mwf", "mxf", "mxl",
        "mxml", "mxs", "mxu", "n-gage", "n3", "n64", "nb", "nbp", "nc", "ncd",
        "nce", "ncx", "nds", "nef", "nes", "nfo", "ngdat", "nlu", "nml", "nnd",
        "nns", "nnw", "not", "npx", "nsc", "nsf", "nsv", "nws", "o", "oa2",
        "oa3", "oas", "obd", "obj", "ocl", "oda", "odb", "odc", "odd", "odf",
        "odft", "odg", "odi", "odm", "odp", "ods", "odt", "odx", "oga", "ogg",
        "ogm", "ogv", "ogx", "old", "oleo", "onepkg", "onetmp", "onetoc", "onetoc2", "opf",
        "opml", "oprc", "ora", "orf", "org", "orq", "ors", "osf", "osfpvg", "otb",
        "otc", "otf", "otg", "oth", "oti", "otm", "otp", "ots", "ott", "owl",
        "oxps", "oxt", "p", "p10", "p12", "p7b", "p7c", "p7m", "p7r", "p7s",
        "p8", "pack", "pak", "par", "par2", "pas", "patch", "paw", "pbd", "pbm",
        "pcd", "pcf", "pcf.gz", "pcf.z", "pcl", "pclxl", "pct", "pcurl", "pcx", "pdb",
        "pdc", "pdf", "pdf.bz2", "pdf.gz", "pdx", "pef", "pem", "perl", "pet", "pfa",
        "pfb", "pfm", "pfr", "pfx", "pgm", "pgn", "pgp", "php", "php3", "pic",
        "pict", "pict1", "pict2", "pk", "pkg", "pkg.tar.gz", "pki", "pkipath", "pko", "pkr",
        "pl", "pla", "plb", "plc", "plf", "pln", "pls", "pm", "pma", "pmc",
        "pml", "pmm", "pmr", "pmw", "png", "pnm", "pntg", "po", "por", "portpkg",
        "pot", "potm", "potx", "pov", "ppa", "ppam", "ppd", "ppm", "pps", "ppsm",
        "ppsx", "ppt", "pptm", "pptx", "ppz", "pqa", "prc", "pre", "prf", "provx",
        "ps", "ps.bz2", "ps.gz", "psb", "psd", "psf", "psf.gz", "pskcxml", "psflib", "psid",
        "pskcxml", "psw", "ptid", "pub", "pup", "pvb", "pw", "pwn", "pwz", "py",
        "pya", "pyc", "pyo", "pyv", "qam", "qbo", "qfx", "qif", "qps", "qt",
        "qtif", "qtl", "qtvr", "qwd", "qwt", "qxb", "qxd", "qxl", "qxt", "ra",
        "raf", "ram", "rar", "ras", "raw", "rax", "rb", "rcprofile", "rct", "rdf",
        "rdf-crypt", "rdfs", "rdz", "readme", "reg", "rej", "relo", "rep", "res", "rgb",
        "rif", "rip", "rl", "rlc", "rld", "rle", "rm", "rmi", "rmj", "rmm",
        "rmp", "rms", "rmvb", "rmx", "rnc", "rnd", "roa", "roff", "rp", "rp9",
        "rpm", "rpss", "rpst", "rq", "rs", "rsd", "rsheet", "rss", "rt", "rtf",
        "rtx", "rv", "rvx", "s", "s3m", "sac", "saf", "sam", "sami", "sav",
        "sbml", "sc", "scd", "scm", "scq", "scs", "sct", "scurl", "sda", "sdc",
        "sdd", "sdkd", "sdkm", "sdp", "sds", "sdw", "see", "seed", "sema", "semd",
        "semf", "ser", "setpay", "setreg", "sfd-hdstx", "sfs", "sgf", "sgi", "sgl", "sgm",
        "sgml", "sh", "shar", "shf", "shn", "si", "siag", "sic", "sid", "sieve",
        "sig", "sik", "silo", "sis", "sisx", "sit", "sitx", "siv", "sk", "skd",
        "sk1", "skm", "skp", "skr", "skt", "sl", "slc", "sldm", "sldx", "slk",
        "slt", "smaf", "smc", "smd", "smf", "smi", "smil", "sml", "sms", "snd",
        "snf", "so", "soa", "soap", "spc", "spd", "spec", "spf", "spl", "spot",
        "spp", "spq", "spx", "sql", "sr2", "src", "srf", "srt", "sru", "srx",
        "ssa", "sse", "ssf", "ssml", "st", "stc", "std", "stf", "sti", "stk",
        "stl", "stm", "str", "stw", "sty", "sub", "sun", "sus", "susp", "sv4cpio",
        "sv4crc", "svd", "svg", "svgz", "swa", "swf", "swi", "sxc", "sxd", "sxg",
        "sxi", "sxm", "sxw", "sylk", "t", "t2t", "taf", "tao", "tar", "tar.bz",
        "tar.bz2", "tar.gz", "tar.lzma", "tar.lzo", "tar.xz", "tar.z", "tau", "tbz", "tbz2",
        "tcap", "tcl", "tcu", "td", "teacher", "tei", "ter", "tex", "texi", "texinfo",
        "", "tfi", "tfm", "tga", "tgz", "theme", "themepack", "thmx", "tif", "tiff",
        "tk", "tlz", "tmo", "tnef", "tnf", "toc", "torrent", "tpic", "tpl", "tpt",
        "tr", "tra", "trm", "ts", "tsa", "tsd", "tsq", "tsr", "tsv", "tta",
        "ttc", "ttf", "ttl", "ttml", "ttx", "tuc", "tur", "twd", "twds", "txd",
        "txf", "txt", "txz", "tzo", "u32", "udeb", "ufd", "ufdl", "ufraw", "ui",
        "uil", "uis", "ult", "umj", "uni", "unityweb", "uoml", "uri", "url", "urls",
        "ustar", "utz", "uu", "uva", "uvh", "uvi", "uvm", "uvp", "uvs", "uvu",
        "uvv", "vala", "vapi", "vcard", "vcd", "vcf", "vcg", "vcs", "vct", "vcx",
        "vda", "vhd", "vhdl", "vide", "vis", "viv", "vivo", "vlc", "vob", "voc",
        "vor", "vox", "vrml", "vsd", "vsf", "vss", "vst", "vsw", "vtu", "vxml",
        "w3d", "wad", "wav", "wax", "wb1", "wb2", "wb3", "wbmp", "wbs", "wbxml",
        "wcm", "wdb", "weba", "webm", "webp", "wg", "wgt", "wiz", "wk1", "wk3",
        "wk4", "wks", "wlnk", "wm", "wma", "wmd", "wmf", "wml", "wmlc", "wmls",
        "wmlsc", "wmv", "wmx", "wmz", "woff", "wp", "wp4", "wp5", "wp6", "wpd",
        "wpg", "wpl", "wpp", "wps", "wqd", "wri", "wrl", "wsdl", "wspolicy", "wtb",
        "wv", "wvc", "wvp", "wvx", "wwf", "x32", "x3d", "x3f", "xac", "xap",
        "xar", "xbap", "xbd", "xbel", "xbl", "xbm", "xcf", "xcf.bz2", "xcf.gz", "xcs",
        "xdd", "xdf", "xdm", "xdp", "xdssc", "xdw", "xenc", "xer", "xfdf", "xfdl",
        "xht", "xhtm", "xhtml", "xi", "xif", "xla", "xlam", "xlb", "xlc", "xld",
        "xlf", "xliff", "xll", "xlm", "xls", "xlsb", "xlsm", "xlsx", "xlt", "xltm",
        "xltx", "xlw", "xm", "xmf", "xmi", "xml", "xmls", "xo", "xop", "xpdl",
        "xpi", "xpm", "xpr", "xps", "xpw", "xpx", "xsf", "xsl", "xslfo", "xslt",
        "xsm", "xspf", "xul", "xvm", "xvml", "xwd", "xyz", "xz", "yaml", "yang",
        "yin", "z", "zabw", "zaz", "zip", "zir", "zirz", "zmm", "zone", "zoo"
};

static const char *mime_types[] = {
        "directory", "vnd.lotus-1-2-3", "x-ext2-", "h323", "x-3ds", "vnd.in3d.3dml", "x-ext3-", "3gpp", "3gpp", "3gpp",
        "3gpp", "x-ext4-", "x-t602", "x-mod", "x-7z-compressed", "x-archive", "A2L", "x-authorware-bin", "mp4", "x-authorware-map",
        "x-authorware-seg", "x-abiword", "x-abiword", "pkix-attr-cert", "ac3", "vnd.americandynamics.acc", "x-ace", "vnd.acucobol", "vnd.acucocorp", "internet-property-stream",
        "x-adasrc", "adpcm", "x-adasrc", "vnd.graph", "x-font-afm", "vnd.ibm.modcap", "x-applix-graphics", "vnd.ahead.space", "postscript", "x-aiff",
        "x-aiff", "x-aiff", "vnd.adobe.air--installer-package+zip", "vnd.dvb.ait", "x-perl", "x-alz", "vnd.amiga.ami", "AML", "AMR", "x-amzxml",
        "x-navi-animation", "x-anim", "x-anim", "x-anim", "x-anim", "x-anim", "x-anim", "x-anim", "x-anim", "x-anim",
        "x-anim", "x-anim", "x-anim", "annodex", "x-ape", "vnd.android.package-archive", "x-ms-", "vnd.lotus-approach", "auth-policy+xml", "x-arj",
        "x-sony-arw", "x-applix-spreadsheet", "plain", "x-ms-asf", "x-asm", "vnd.accpac.simply.aso", "x-asp", "x-ms-asf", "x-ssa", "x-ms-asf",
        "vnd.acucorp", "ATF", "ATFX", "atom+xml", "atomcat+xml", "atomdeleted+xml", "atomsvc+xml", "vnd.antix.game-component", "ATXML", "basic",
        "tamp-apex-update-confirm", "x-authors", "x-ms", "applixware", "AMR-WB", "x-awk", "annodex", "olescript", "annodex", "vnd.airzip.filesecure.azf",
        "vnd.airzip.filesecure.azs", "vnd.amazon.ebook", "x-bacon", "x-trash", "plain", "x-msdownload", "x-bcpio", "x-font-bdf", "vnd.syncml.dm+wbxml", "vnd.realvnc.bed",
        "x-bfe", "vnd.fujitsu.oasysprs", "x-bibtex", "octet-stream", "x-blender", "x-blender", "vnd.bmi", "bmp", "vnd.framemaker", "vnd.previewsystems.box",
        "x-bzip2", "octet-stream", "prs.btif", "x-btrfs-", "x-bzip", "x-bzip", "x-csrc", "x-c++src", "vnd.cluetrust.cartomobile-config", "vnd.cluetrust.cartomobile-config-pkg",
        "vnd.clonk.c4group", "vnd.clonk.c4group", "vnd.clonk.c4group", "vnd.clonk.c4group", "vnd.clonk.c4group", "vnd.ms-cab-compressed", "vnd.curl.car", "vnd.ms-pkiseccat", "x-cb7", "cbor",
        "x-cbr", "x-cbt", "x-cbz", "x-c++src", "ccmp+xml", "x-director", "ccxml+xml", "vnd.contact.cmsg", "x-netcdf", "CDFX+XML",
        "vnd.mediastation.cdkey", "cdmi-capability", "cdmi-container", "cdmi-domain", "cdmi-object", "cdmi-queue", "vnd.corel-draw", "x-cdx", "vnd.chemdraw+xml", "vnd.cinderella",
        "CEA", "cellml+xml", "pkix-cert", "x-x509-ca-cert", "cgm", "x-changelog:ChangeLog", "x-chat", "vnd.ms-htmlhelp", "vnd.kde.kchart", "x-cif",
        "vnd.anser-web-certificate-issue-initiation", "vnd.ms-artgalry", "simple-filter+xml", "vnd.claymore", "java-vm", "vnd.crick.clicker.keyboard", "vnd.crick.clicker.palette", "vnd.crick.clicker.template", "vnd.crick.clicker.wordbank", "vnd.crick.clicker",
        "x-msclip", "x-tex", "x-cmake", "x-cmake", "vnd.cosmocaller", "x-cmdf", "x-cml", "vnd.yellowriver-custom-menu", "cms", "x-cmx",
        "cis-cod", "x-msdownload", "plain", "x-copying", "x-cpio", "x-cpio-compressed", "cpl+xml", "x-c++src", "mac-compactpro", "x-canon-cr2",
        "x-mscardfile", "x-authors", "pkix-crl", "x-x509-ca-cert", "x-canon-crw", "vnd.rig.cryptonote", "x-csharp", "x-csh", "x-csml", "vnd.commonspace",
        "csrattrs", "css", "css", "x-director", "csta+xml", "csv", "cu-seeme", "tamp-community-update-confirm", "x-cue", "x-win-bitmap",
        "vnd.curl", "prs.cww", "prs.cww", "x-director", "x-c++src", "x-dsrc", "vnd.collada+xml", "vnd.mobius.daf", "x-dar", "mpeg",
        "vnd.fdsn.seed", "davmount+xml", "x-dbf", "x-dc-rom", "DCD", "x-dcl", "dicom", "x-kodak-dcr", "vnd.curl.dcurl", "vnd.oma.dd2+xml",
        "vnd.fujixerox.ddd", "x-dds", "x-debian-package", "plain", "x-delta", "octet-stream", "x-x509-ca-cert", "x-desktop", "vnd.dreamfactory", "x-dia-diagram",
        "x-c", "x-patch", "DII", "x-director", "vnd.mobius.dis", "octet-stream", "octet-stream", "DIT", "x-ms", "vnd.djvu",
        "vnd.djvu", "x-msdownload", "octet-stream", "octet-stream", "vnd.dna", "x-adobe-dng", "msword", "docbook+xml", "vnd.openxmlformats-officedocument.wordprocessingml.document", "vnd.openxmlformats-officedocument.wordprocessingml.document",
        "msword-template", "vnd.ms-word.template.macroenabled.12", "vnd.openxmlformats-officedocument.wordprocessingml.template", "vnd.osgi.dp", "vnd.dpgraph", "x-diff", "vnd.dra", "prs.lines.tag", "x-dsl", "dssc+der",
        "x-dtbook+xml", "xml-dtd", "vnd.dts", "vnd.dts.hd", "x-tex", "octet-stream", "dv", "dvcs", "x-dvi", "x-bzdvi",
        "x-gzdvi", "vnd.dwf", "vnd.dwg", "vnd.dxf", "vnd.spotfire.dxp", "x-director", "x-eiffel", "vnd.nuera.ecelp4800", "vnd.nuera.ecelp7470", "vnd.nuera.ecelp9600",
        "ecmascript", "EDI-X12", "vnd.novadigm.edm", "vnd.novadigm.edx", "vnd.picsel", "x-egon", "vnd.pg.osasli", "x-eiffel", "x-eim", "x-emacs-lisp",
        "octet-stream", "x-emf", "rfc822", "emma+xml", "emotionml+xml", "vnd.emusic-emusic_package", "xml-external-parsed-entity", "vnd.digital-winds", "vnd.ms-fontobject", "x-eps",
        "x-bzeps", "x-gzeps", "x-eps", "x-bzeps", "x-gzeps", "x-gzeps", "x-eps", "epub+zip", "x-erlang", "ecmascript",
        "vnd.eszigno3+xml", "vnd.epson.esf", "vnd.eszigno3+xml", "x-e-theme", "x-se", "envoy", "x-ms-dos-executable", "exi", "x-exr", "vnd.novadigm.ext",
        "andrew-inset", "vnd.ezpix-album", "vnd.ezpix-package", "x-fortran", "x-f2fs-", "x-f4v", "x-fortran", "x-fortran", "x-fortran", "x-fictionbook+xml",
        "vnd.fastbidsheet", "vnd.isac.fcs", "vnd.fdf", "fdt+xml", "vnd.denovo.fcselayout-link", "vnd.fujitsu.oasysgp", "x-director", "x-freehand", "x-freehand", "x-freehand",
        "x-freehand", "x-freehand", "fractals", "x-xfig", "fastinfoset", "fits", "fits", "x-fluid", "x-flac", "x-flic",
        "x-fli", "vnd.micrografx.flo", "x-flv", "vnd.kde.kivio", "vnd.fmi.flexstor", "vnd.fly", "vnd.framemaker", "vnd.frogans.fnc", "x-xslfo", "vnd.oasis.opendocument.database",
        "vnd.oasis.opendocument.chart", "vnd.oasis.opendocument.formula", "vnd.oasis.opendocument.graphics", "vnd.oasis.opendocument.", "vnd.oasis.opendocument.-master", "vnd.oasis.opendocument.presentation", "vnd.oasis.opendocument.spreadsheet", "vnd.oasis.opendocument.", "x-fortran", "vnd.fpx",
        "vnd.framemaker", "vnd.fsc.weblaunch", "vnd.fst", "vnd.fluxtime.clip", "vnd.anser-web-funds-transfer-initiation", "fits", "vnd.fvt", "vnd.adobe.fxp", "vnd.fuzzysheet", "vnd.geoplan",
        "g3fax", "vnd.geospace", "vnd.groove-account", "x-gameboy-rom", "x-gba-rom", "rpki-ghostbusters", "directory", "vnd.gdl", "x-gedcom", "x-gedcom",
        "x-genesis-rom", "vnd.dynageo", "vnd.geometry-explorer", "x-tex-gf", "x-sms-rom", "vnd.geogebra.file", "vnd.geogebra.tool", "vnd.groove-help", "gif", "vnd.groove-identity-",
        "x-glade", "x-get-translation", "vnd.gmx", "x-gnucash", "gnunet-directory", "x-gnucash", "x-gnumeric", "x-gnuplot", "x-gnuplot", "pgp-encrypted",
        "vnd.flographit", "x-gnuplot", "vnd.grafeq", "vnd.grafeq", "x-graphite", "srgs", "vnd.geometry-explorer", "vnd.groove-injector", "srgs+xml", "x-genie",
        "x-font-type1", "urc-grpsheet+xml", "x-gsm", "x-tar", "x-gtkrc", "vnd.groove-tool-", "vnd.gtw", "vnd.graphviz", "x-google--pointer", "vnd.geonext",
        "gzip", "x-chdr", "x-c++hdr", "h261", "h263", "h264", "vnd.hal+xml", "vnd.hbci", "x-hdf", "held+xml",
        "x-c++hdr", "winhlp", "x-c++hdr", "vnd.hp-hpgl", "vnd.hp-hpid", "x-c++hdr", "vnd.hp-hps", "prs.hpub+zip", "mac-binhex40", "x-haskell",
        "hta", "x-component", "vnd.kenameaapp", "html", "html", "webviewhtml", "vnd.yamaha.hv-dic", "vnd.yamaha.hv-voice", "vnd.yamaha.hv-script", "x-hwp",
        "x-hwt", "x-c++hdr", "vnd.intergeo", "x-ica", "x-tga", "vnd.iccprofile", "vnd.iccprofile", "x-icns", "vnd.microsoft.icon", "calendar",
        "x-idl", "ief", "calendar", "x-iff", "vnd.shana.informed.formdata", "iges", "vnd.igloader", "vnd.insors.igm", "iges", "vnd.micrografx.igx",
        "vnd.shana.informed.interchange", "x-iphone", "x-ilbm", "x-iMelody", "vnd.accpac.simply.imp", "vnd.ms-ims", "x-iMelody", "plain", "inkml+xml", "inkml+xml",
        "x-install", "x-tex", "ipfix", "vnd.shana.informed.package", "x-iptables", "vnd.ibm.rights-management", "vnd.irepository.package+xml", "x-cd-", "x-cd-", "x-internet-signup",
        "x-it", "vnd.shana.informed.formtemplate", "its+xml", "x-zipped-it", "vnd.immervision-ivp", "vnd.immervision-ivu", "jp2", "vnd.sun.j2me.app-descriptor", "vnd.jam", "java-archive",
        "x-java-source", "pipeg", "vnd.jisp", "vnd.hp-jlyt", "x-jng", "x-java-jnlp-file", "vnd.joost.joda-archive", "jp2", "jp2", "jpeg",
        "jpeg", "jp2", "jpeg", "jpm", "jpeg", "jpm", "x-jbuilder-project", "jp2", "jrd+json", "javascript",
        "json", "json-patch+json", "ld+json", "x-kodak-k25", "midi", "vnd.kde.karbon", "x-kodak-kdc", "x-desktop", "x-kexiproject-sqlite3", "x-kexi-connectiondata",
        "x-kexiproject-shortcut", "vnd.kde.kformula", "vnd.kidspiration", "x-killustrator", "smil", "vnd.google-earth.kml+xml", "vnd.google-earth.kmz", "vnd.kinar", "vnd.kinar", "vnd.kde.kontour",
        "x-kpover", "vnd.kde.kpresenter", "x-kpresenter", "x-krita", "plain", "vnd.kde.kspread", "vnd.kahootz", "ktx", "vnd.kahootz", "x-kugar",
        "vnd.kde.kword", "x-kword", "x-shared-library-la", "vnd.las.las+xml", "x-latex", "vnd.llamagraphics.life-balance.desktop", "vnd.llamagraphics.life-balance.exchange+xml", "x-ldif", "vnd.hhe.lesson-player", "x-lha",
        "x-literate-haskell", "x-lhz", "x-copying", "vnd.route66.link66+xml", "plain", "vnd.ibm.modcap", "vnd.ibm.modcap", "x-log", "lostsync+xml", "lost+xml",
        "octet-stream", "vnd.ms-lrm", "x-la-asf", "x-la-asf", "vnd.frogans.ltf", "x-tex", "x-lua", "vnd.lucent.voice", "x-lwo", "x-lwo",
        "vnd.lotus-wordpro", "x-lws", "LXF", "x-lilypond", "x-lyx", "x-lzip", "x-lha", "x-lzma", "x-lzop", "x-objcsrc",
        "x-msmediaview", "x-msmediaview", "x-mod", "mpeg", "mp21", "mpeg", "mpeg", "mpeg", "mpeg", "x-mpegurl",
        "vnd.apple.mpegurl", "x-m4", "mp4", "x-m4b", "vnd.mpegurl", "mp4", "mathematica", "x-markaby", "mads+xml", "vnd.ecowin.chart",
        "x-makefile", "vnd.framemaker", "x-troff-man", "mathml+xml", "mathematica", "vnd.mobius.mbk", "mbox", "vnd.medcalcdata", "vnd.mcd", "vnd.curl.mcurl",
        "x-genesis-rom", "vnd.ms-access", "vnd.ms-modi", "x-zipped-mod", "troff", "x-mod", "mesh", "metalink4+xml", "metalink+xml", "mets+xml",
        "MF4", "vnd.mfmp", "rpki-manifest", "x-magicpoint", "vnd.proteus.magazine", "related", "related", "midi", "midi", "vnd.mif",
        "rfc822", "x-minipsf", "x-matroska", "x-matroska", "x-matroska", "mj2", "mj2", "x-ocaml", "x-ocaml", "vnd.dolby.mlp",
        "x-troff-mm", "vnd.chipnuts.karaoke-mmd", "vnd.smaf", "mathml+xml", "vnd.fujixerox.edmics-mmr", "x-mng", "x-msmoney", "x-get-translation", "x-mo3", "x-mobipocket-ebook",
        "x-moc", "x-mod", "mods+xml", "x-mof", "quicktime", "quicktime", "x-sgi-movie", "x-musepack", "mpeg", "mp21",
        "mpeg", "mp3", "mp4", "mp4", "mp4", "mp4", "mpeg", "x-musepack", "dash+xml", "dashdelta",
        "mpeg", "mpeg", "media-policy-dataset+xml", "mpeg", "mp4", "mpeg", "vnd.apple.installer+xml", "vnd.blueice.multipass", "vnd.mophun.", "vnd.ms-project",
        "vnd.ms-project", "mpeg", "vnd.ibm.minipay", "vnd.mobius.mqy", "marc", "marcxml+xml", "x-mrml", "x-mrml", "x-minolta-mrw", "x-troff-ms",
        "mediaservercontrol+xml", "vnd.fdsn.mseed", "vnd.mseq", "vnd.epson.msf", "vnd.ms-outlook", "mesh", "x-msi", "vnd.mobius.msl", "x-msod", "vnd.muvee.style",
        "x-msx-rom", "x-mod", "vnd.mts", "x-mup", "vnd.musician", "vnd.recordare.musicxml+xml", "x-ms-mediaview", "vnd.mfer", "mxf", "vnd.recordare.musicxml",
        "xv+xml", "vnd.triscape.mxs", "vnd.mpegurl", "vnd.nokia.n-gage.symbian.install", "n3", "x-n64-rom", "mathematica", "vnd.wolfram.player", "x-netcdf", "notecase-plain",
        "notecase-enc", "x-dtbncx+xml", "x-nintendo-ds-rom", "x-nikon-nef", "x-nes-rom", "x-nfo", "vnd.nokia.n-gage.data", "vnd.neurolanguage.nlu", "vnd.enliven", "vnd.noblenet-directory",
        "vnd.noblenet-sealer", "vnd.noblenet-web", "x-mup", "vnd.net-fpx", "x-netshow-channel", "vnd.lotus-notes", "x-nsv", "rfc822", "x-object", "vnd.fujitsu.oasys2",
        "vnd.fujitsu.oasys3", "vnd.fujitsu.oasys", "x-msbinder", "x-tgif", "x-ocl", "ODA", "vnd.oasis.opendocument.database", "vnd.oasis.opendocument.chart", "tei+xml", "vnd.oasis.opendocument.formula",
        "vnd.oasis.opendocument.formula-template", "vnd.oasis.opendocument.graphics", "vnd.oasis.opendocument.", "vnd.oasis.opendocument.-master", "vnd.oasis.opendocument.presentation", "vnd.oasis.opendocument.spreadsheet", "vnd.oasis.opendocument.", "ODX", "ogg", "ogg",
        "x-ogm+ogg", "ogg", "ogg", "x-trash", "x-oleo", "onenote", "onenote", "onenote", "onenote", "oebps-package+xml",
        "x-opml+xml", "vnd.palm", "openraster", "x-olympus-orf", "vnd.lotus-organizer", "ocsp-request", "ocsp-response", "vnd.yamaha.openscoreformat", "vnd.yamaha.openscoreformat.osfpvg+xml", "vnd.oasis.opendocument.database-template",
        "vnd.oasis.opendocument.chart-template", "vnd.oasis.opendocument.formula-template", "vnd.oasis.opendocument.graphics-template", "vnd.oasis.opendocument.-web", "vnd.oasis.opendocument.-template", "vnd.oasis.opendocument.-master-template", "vnd.oasis.opendocument.presentation-template", "vnd.oasis.opendocument.spreadsheet-template", "vnd.oasis.opendocument.-template", "rdf+xml",
        "oxps", "vnd.openofficeorg.extension", "x-pascal", "pkcs10", "x-pkcs12", "x-pkcs7-certificates", "pkcs7-mime", "pkcs7-mime", "x-pkcs7-certreqresp", "pkcs7-signature",
        "pkcs8", "x-java-pack200", "x-pak", "plain-bas", "x-par2", "x-pascal", "x-patch", "vnd.pawaafile", "vnd.powerbuilder6", "x-portable-bitmap",
        "x-photo-cd", "x-font-pcf", "x-font-pcf", "x-font-pcf", "vnd.hp-pcl", "vnd.hp-pclxl", "x-pict", "vnd.curl.pcurl", "x-pcx", "x-palm-database",
        "x-aportisdoc", "pdf", "x-bzpdf", "x-gzpdf", "PDX", "x-pentax-pef", "x-x509-ca-cert", "x-perl", "pet", "x-font-type1",
        "x-font-type1", "x-font-type1", "font-tdpfr", "x-pkcs12", "x-portable-graymap", "x-chess-pgn", "pgp-encrypted", "x-php", "x-php", "x-pict",
        "x-pict", "x-pict", "x-pict", "x-tex-pk", "octet-stream", "x-pkg", "pkixcmp", "pkix-pkipath", "vnd.ms-pkipko", "pgp-keys",
        "x-perl", "x-iriver-pla", "vnd.3gpp.pic-bw-large", "vnd.mobius.plc", "vnd.pocketlearn", "x-planperfect", "pls+xml", "x-perl", "x-perfmon", "x-perfmon",
        "vnd.ctc-posml", "x-portable-multimap", "x-perfmon", "x-perfmon", "png", "x-portable-anymap", "x-macpaint", "x-get-translation", "x-spss-por", "vnd.macports.portpkg",
        "x-get-translation-template", "vnd.ms-powerpoint.template.macroenabled.12", "vnd.openxmlformats-officedocument.presentationml.template", "x-povray", "vnd.ms-powerpoint", "vnd.ms-powerpoint.addin.macroenabled.12", "vnd.cups-ppd", "x-portable-pixmap", "vnd.ms-powerpoint", "vnd.openxmlformats-officedocument.presentationml.presentation",
        "vnd.openxmlformats-officedocument.presentationml.presentation", "vnd.ms-powerpoint", "vnd.openxmlformats-officedocument.presentationml.presentation", "vnd.openxmlformats-officedocument.presentationml.presentation", "vnd.ms-powerpoint", "vnd.palm", "x-palm-database", "vnd.lotus-freelance", "pics-rules", "provenance+xml",
        "postscript", "x-bzpostscript", "x-gzpostscript", "vnd.3gpp.pic-bw-small", "vnd.adobe.photoshop", "x-font-linux-psf", "x-gz-font-linux-psf", "pskc+xml", "x-psflib", "prs.sid",
        "pskc+xml", "x-pocket-word", "vnd.pvi.ptid1", "x-mspublisher", "pup", "vnd.3gpp.pic-bw-var", "x-pw", "vnd.3m.post-it-notes", "vnd.ms-powerpoint", "x-python",
        "vnd.ms-playready.media.pya", "x-python-bytecode", "x-python-bytecode", "vnd.ms-playready.media.pyv", "vnd.epson.quickanime", "vnd.intu.qbo", "vnd.intu.qfx", "x-qw", "vnd.publishare-delta-tree", "quicktime",
        "x-quicktime", "x-quicktime-media-link", "quicktime", "vnd.quark.quarkxpress", "vnd.quark.quarkxpress", "vnd.quark.quarkxpress", "vnd.quark.quarkxpress", "vnd.quark.quarkxpress", "vnd.quark.quarkxpress", "vnd.rn-real",
        "x-fuji-raf", "ram", "x-rar", "x-cmu-raster", "x-panasonic-raw", "vnd.rn-real", "x-ruby", "vnd.ipunplugged.rcprofile", "prs.nprend", "rdf+xml",
        "prs.rdf-xml-crypt", "rdf+xml", "vnd.data-vision.rdz", "x-readme", "x-ms-regedit", "x-reject", "p2p-overlay+xml", "vnd.businessobjects", "x-dtbresource+xml", "x-rgb",
        "reginfo+xml", "vnd.rip", "resource-lists+xml", "vnd.fujixerox.edmics-rlc", "resource-lists-diff+xml", "rle", "vnd.rn-realmedia", "mid", "vnd.rn-realmedia", "vnd.rn-realmedia",
        "x-pn-real-plugin", "vnd.rn-realmedia", "vnd.rn-realmedia", "vnd.rn-realmedia", "relax-ng-compact-syntax", "prs.nprend", "rpki-roa", "troff", "vnd.rn-realpix", "vnd.cloanto.rp9",
        "x-rpm", "vnd.nokia.radio-presets", "vnd.nokia.radio-preset", "sparql-query", "rls-services+xml", "rsd+xml", "urc-ressheet+xml", "rss+xml", "vnd.rn-real", "rtf",
        "rich", "vnd.rn-real", "vnd.rn-real", "x-asm", "x-s3m", "tamp-sequence-adjust-confirm", "vnd.yamaha.smaf-", "x-amipro", "x-sami", "x-spss-sav",
        "sbml+xml", "vnd.ibm.secure-container", "x-msschedule", "x-scheme", "scvp-cv-request", "scvp-cv-response", "scriptlet", "vnd.curl.scurl", "vnd.stardivision.draw", "vnd.stardivision.calc",
        "vnd.stardivision.impress", "vnd.solent.sdkm+xml", "vnd.solent.sdkm+xml", "vnd.stardivision.impress", "vnd.stardivision.chart", "vnd.stardivision.writer", "vnd.seemail", "vnd.fdsn.seed", "vnd.sema", "vnd.semd",
        "vnd.semf", "java-serialized-object", "set-payment-initiation", "set-registration-initiation", "vnd.hydrostatix.sof-data", "x-squashfs-", "x-go-sgf", "x-sgi", "vnd.stardivision.writer", "sgml",
        "sgml", "x-shellscript", "x-shar", "shf+xml", "x-shorten", "vnd.wap.si", "x-siag", "vnd.wap.sic", "prs.sid", "sieve",
        "pgp-signature", "x-trash", "mesh", "vnd.symbian.install", "vnd.symbian.install", "x-stuffit", "x-stuffitx", "sieve", "x-skencil", "vnd.koan",
        "x-skencil", "vnd.koan", "vnd.koan", "pgp-keys", "vnd.koan", "vnd.wap.sl", "vnd.wap.slc", "vnd.ms-powerpoint.slide.macroenabled.12", "vnd.openxmlformats-officedocument.presentationml.slide", "spreadsheet",
        "vnd.epson.salt", "x-smaf", "x-snes-rom", "vnd.stardivision.mail", "vnd.stardivision.math", "smil", "smil", "smil", "x-sms-rom", "basic",
        "x-font-snf", "x-sharedlib", "dns", "soap+xml", "x-pkcs7-certificates", "x-font-speedo", "x-rpm-spec", "vnd.yamaha.smaf-phrase", "x-shockwave-flash", "vnd.in3d.spot",
        "scvp-vp-response", "scvp-vp-request", "speex", "x-sql", "x-sony-sr2", "x-wais-source", "x-sony-srf", "x-subrip", "sru+xml", "sparql-results+xml",
        "x-ssa", "vnd.kodak-descriptor", "vnd.epson.ssf", "ssml+xml", "vnd.sailingtracker.track", "vnd.sun.xml.calc.template", "vnd.sun.xml.draw.template", "vnd.wt.stf", "vnd.sun.xml.impress.template", "hyperstudio",
        "vnd.ms-pki.stl", "x-stm", "vnd.pg.format", "vnd.sun.xml.writer.template", "x-tex", "x-microdvd", "x-sun-raster", "vnd.sus-calendar", "vnd.sus-calendar", "x-sv4cpio",
        "x-sv4crc", "vnd.svd", "svg+xml", "svg+xml-compressed", "x-director", "x-shockwave-flash", "vnd.arastra.swi", "vnd.sun.xml.calc", "vnd.sun.xml.draw", "vnd.sun.xml.writer.global",
        "vnd.sun.xml.impress", "vnd.sun.xml.math", "vnd.sun.xml.writer", "spreadsheet", "troff", "x-txt2tags", "x-adrift", "vnd.tao.intent-module-archive", "x-tar", "x-bzip-compressed-tar",
        "x-bzip-compressed-tar", "x-compressed-tar", "x-lzma-compressed-tar", "x-tzo", "x-xz-compressed-tar", "x-tarz", "tamp-apex-update", "x-bzip-compressed-tar", "x-bzip-compressed-tar", "vnd.3gpp2.tcap",
        "x-tcl", "tamp-community-update", "urc-targetdesc+xml", "vnd.smart.teacher", "tei+xml", "tamp-error", "x-tex", "x-texinfo", "x-texinfo",
        "plain", "thraud+xml", "x-tex-tfm", "x-tga", "x-compressed-tar", "x-theme", "x-windows-themepack", "vnd.ms-officetheme", "tiff", "tiff",
        "x-tcl", "x-lzma-compressed-tar", "vnd.tmobile-livetv", "vnd.ms-tnef", "vnd.ms-tnef", "x-cdrdao-toc", "x-bittorrent", "x-tga", "vnd.groove-tool-template", "vnd.trid.tpt",
        "troff", "vnd.trueapp", "x-msterminal", "x-linguist", "tamp-sequence-adjust", "timestamped-data", "tamp-status-query", "tamp-status-response", "tab-separated-values", "x-tta",
        "x-font-ttf", "x-font-ttf", "turtle", "ttml+xml", "x-font-ttx", "tamp-update-confirm", "tamp-update", "vnd.simtech-mindmapper", "vnd.simtech-mindmapper", "vnd.genomatix.tuxedo",
        "vnd.mobius.txf", "plain", "x-xz-compressed-tar", "x-tzo", "x-authorware-bin", "x-debian-package", "vnd.ufdl", "vnd.ufdl", "x-ufraw", "x-designer",
        "x-uil", "urc-uisocketdesk+xml", "x-mod", "vnd.umajin", "x-mod", "vnd.unity", "vnd.uoml+xml", "uri-list", "uri-list", "uri-list",
        "x-ustar", "vnd.uiq.theme", "x-uuencode", "vnd.dece.", "vnd.dece.hd", "vnd.dece.graphic", "vnd.dece.mobile", "vnd.dece.pd", "vnd.dece.sd", "vnd.uvvu.mp4",
        "vnd.dece.", "x-vala", "x-vala", "vcard", "x-cdlink", "directory", "vnd.groove-vcard", "calendar", "directory", "vnd.vcx",
        "x-tga", "x-vhdl", "x-vhdl", "x-vide", "vnd.visionary", "vivo", "vivo", "x-mpegurl", "mpeg", "x-voc",
        "vnd.stardivision.writer", "x-authorware-bin", "vrml", "vnd.visio", "vnd.vsf", "vnd.visio", "x-tga", "vnd.visio", "vnd.vtu", "voicexml+xml",
        "x-director", "x-doom", "x-wav", "x-ms-asx", "x-quattropro", "x-quattropro", "x-quattropro", "vnd.wap.wbmp", "vnd.criticaltools.wbs+xml", "vnd.wap.wbxml",
        "vnd.ms-works", "vnd.ms-works", "webm", "webm", "webp", "vnd.pmi.widget", "widget", "msword", "vnd.lotus-1-2-3", "vnd.lotus-1-2-3",
        "vnd.lotus-1-2-3", "vnd.ms-works", "link-format", "x-ms-wm", "x-ms-wma", "x-ms-wmd", "x-wmf", "vnd.wap.wml", "vnd.wap.wmlc", "vnd.wap.wmlscript",
        "vnd.wap.wmlscriptc", "x-ms-wmv", "x-ms-wmx", "x-ms-wmz", "font-woff", "vnd.wordperfect", "vnd.wordperfect", "vnd.wordperfect", "vnd.wordperfect", "vnd.wordperfect",
        "x-wpg", "vnd.ms-wpl", "vnd.wordperfect", "vnd.ms-works", "vnd.wqd", "x-mswrite", "vrml", "wsdl+xml", "wspolicy+xml", "vnd.webturbo",
        "x-wavpack", "x-wavpack-correction", "x-wavpack", "x-ms-wvx", "x-wwf", "x-authorware-bin", "vnd.hzn-3d-crossword", "x-sigma-x3f", "x-gnucash", "x-silverlight-app",
        "vnd.xara", "x-ms-xbap", "vnd.fujixerox.docuworks.binder", "x-xbel", "xml", "x-xbitmap", "x-xcf", "x-compressed-xcf", "x-compressed-xcf", "calendar+xml",
        "bacnet-xdd+zip", "xcap-diff+xml", "vnd.syncml.dm+xml", "vnd.adobe.xdp+xml", "dssc+xml", "vnd.fujixerox.docuworks", "xenc+xml", "patch-ops-error+xml", "vnd.adobe.xfdf", "vnd.xfdl",
        "xhtml+xml", "xhtml+xml", "xhtml+xml", "x-xi", "vnd.xiff", "vnd.ms-excel", "vnd.ms-excel.addin.macroenabled.12", "vnd.ms-excel", "vnd.ms-excel", "vnd.ms-excel",
        "x-xliff", "x-xliff", "vnd.ms-excel", "vnd.ms-excel", "vnd.ms-excel", "vnd.openxmlformats-officedocument.spreadsheetml.sheet", "vnd.openxmlformats-officedocument.spreadsheetml.sheet", "vnd.openxmlformats-officedocument.spreadsheetml.sheet", "vnd.ms-excel", "vnd.ms-excel.template.macroenabled.12",
        "vnd.openxmlformats-officedocument.spreadsheetml.template", "vnd.ms-excel", "x-xm", "x-xmf", "x-xmi", "xml", "dskpp+xml", "vnd.olpc-sugar", "xop+xml", "xml",
        "x-xpinstall", "x-xpixmap", "vnd.is-xpr", "vnd.ms-xpsdocument", "vnd.intercon.formnet", "vnd.intercon.formnet", "prs.xsf+xml", "xml", "x-xslfo", "xslt+xml",
        "vnd.syncml+xml", "xspf+xml", "vnd.mozilla.xul+xml", "xv+xml", "xv+xml", "x-xwindowdump", "x-xyz", "x-xz", "yaml", "yang",
        "yin+xml", "x-compress", "x-abiword", "vnd.zzazz.deck+xml", "zip", "vnd.zul", "vnd.zul", "vnd.handheld-entertainment+xml", "dns", "x-zoo"
};

#define FILE_LIST_SIZE 1418

const char* determine_mime_type(const char* filename) {
   const char* extension = strrchr(filename, '.');
   if (extension == NULL) {
       return "text/plain";
   }
   ++extension;
    for (int i = 0; i < FILE_LIST_SIZE; ++i) {
        if (strcasecmp(extension, mime_extensions[i]) == 0) {
            return mime_types[i];
        }
    }
    return "text/plain";
}
